# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)
# Recipe.create!(title: "Steakhouse Dinner", description: "A dinner perfect for a date night at home! Just like you would find in the best steakhouses.", ingredients: "one 2-3 inch thick bone in porterhouse steak, 2 baking potatoes, one head iceberg lettuce, 6 strips bacon, bleu cheese dressing, maldon salt for finishing the steak", instructions: "Let steak sit out for 3-4 hours to come to room temp. Meanwhile, cook bacon in a heavy skillet unitl crisp and set aside. Scrub potatoes and prick with a fork. Put potatoes into a cold oven and set the temp to 450 degrees F. Roast for 90 minutes. For the steak, heat a large, heavy bottom skillet over high heat. When skillet is rocket hot, sear the steak on one side for 5-6 minutes. Flip and sear the other side an additional 5 minutes.  Place steak on the fat cap and place in a 350 degree oven for 5-6  minutes to finish cooking to medium rare. While the steak is resting on a cutting board, prepare the wedge salad. Cut iceberg lettuce in half and place each half in a shallow bowl. Put bleu cheese dressing and crumbled bacon on top. Grind fresh black pepper over the top. Slice the steak along the grain and plate several pieces from each part (filet and strip) on each plate. Put a baked potato next to the steak and serve with butter and sour cream.", image_url: "https://images.pexels.com/photos/5213972/pexels-photo-5213972.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")

# Recipe.create!(title: "Gail's Awesome Brownies", description: "Rich, chocolatey brownies", ingredients: "2/3 c unsweetened cocoa powder, 1 1/2 c granulated sugar, 1/3 c powdered sugar, 1/2 tsp salt, 1 c all purpose flour, 1 c chocolate chips (optional), 3 large eggs, 1/2 c vegetable oil, 2 Tbsp water, 2 tsp pure vanilla extract", instructions: " 
#     1. Preheat oven to 350 degrees. Line a 9 x 9 in square pan with foil or parchment paper, leaving a couple of inches overhang on two sides (to allow easy removal of brownies). Grease the foil or parchment. 
#     2. In a lg bowl, combine cocoa powder, sugars, salt, flour, and chocolate chips. Whisk until combined. Add eggs, oil, water and vanilla and stir with a rubber spatula until combined (it will be thick).
#     3. Pour the batter into the prepared pan and smooth the top. Bake 35-45 mins (begin checking at 30 mins with toothpick). Brownies are done when toothpick inserted comes out without raw batter on it. Be careful not to overbake. Remove and place on cooling rack.", image_url: "https://images.pexels.com/photos/7157867/pexels-photo-7157867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")

# Recipe.create!(title: " Garlic Hummus", description: "Creamy, garlicky hummus", ingredients: "8-10 roasted garlic cloves, 4 T garlic olive oil or plain olive oil, 16 oz cooked chickpeas, 6-8 oz (about 1 cup) tahini paste, salt to taste, 1/4 c lemon juice, 5 T plus 2 tsp ice cold water", instructions: "1. Set about 1/3 cup chickpeas aside in a bowl. Add remaining chickpeas, tahini paste, roasted garlic cloves, pinch of salt, and lemon juice to the bowl of a food processor. Blitz until smooth, about 2-3 mins.
#     2. With the machine running, slowly drizzle in the ice water until smooth and aerated. You may have to add a bit more cold water. Adjust seasoning.
#     3. Add 2 T oil and a pinch of salt to the bowl with reserved chickpeas and stir to combine.
#     4. Transfer hummus to a shallow platter and smooth it. Create a well in the center. Spoon reserved chickpeas in the center. Top all with a drizzle of olive oil. You can also sprinkle with zaataar seasoning or smoked paprika. Serve with pita chips and crudite.", image_url: "https://images.pexels.com/photos/6252726/pexels-photo-6252726.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")

# Recipe.create!(title: "Roasted Carrot Soup", description: "A spicy, creamy soup without the guilt", ingredients: "about 1 lb carrots, washed, dried, and cut into 1 in thick coins, 1 T coconut or olive oil, 1/2 T garam masala, 5 garlic cloves (smashed with skin left on), 1/2 inch knob fresh ginger, 1/2 large onion cut into quarters and separated, 3 c good quality vegetable or chicken stock (hot), 1 can coconut milk, 1/2 c fresh carrot juice, juice of 1 medium sized lime, sea salt to taste, 1 tsp turmeric, pinch of cayenne pepper to taste", instructions: "1. Preheat oven to 400-425 degrees. On a large sheet pan lined with a silicon mat add carrots and onion. Drizzle olive oid over and sprinkle with garam masala and salt. Massage into the veggies.
#     2. Roast veggies 30-35 mins, turning halfway through, until veggies are roasted. Remove from oven and remove skins from garlic.
#     3. In a large blender, add all remaining ingredients with roasted veggies. Make sure broth is very hot. Blend until creamy and smooth. Taste and adjust seasonings. Garnish with chives, dill, roasted pumpkin seeds or pinch of cayenne", image_url: "https://images.pexels.com/photos/7656553/pexels-photo-7656553.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")

# Recipe.create!(title: "Pulled Pork Nachos", description: "Delicious nachos perfect for a fall football game", ingredients: "8 oz thick tortilla chips (like El Milagro or El Ranchero brand, 8 oz smoked pork butt or shoulder, shredded, 8 oz cooked black beans,  8-10 oz Chihuahua cheese, shredded, avocado or guacamole, sour cream and your favorite salsa for serving.", instructions: "1. Preheat oven to 375 degrees. Place tortilla chips on a jelly roll baking pan in a thick layer. Top with shredded pork, black beans, and cheese. 2. Bake for 20-25 mins, checking halfway. 3. Remove from oven and place on a serving tray. Serve with avocado, sour cream and salsa.", image_url: "https://images.pexels.com/photos/1108775/pexels-photo-1108775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")

# Beer.create!(name: "Dovetail Maibock", style: "Maibock", description: "A hazy, golden beer with fluffy white head. Well balanced with doughy malt, pale grain, honey, with a hint of grassy hops. Slightly floral aspect.", image_url: "https://cdn.bevv.com/spree/images/attachments/000/011/368/large/Maibock.jpg?1609793216")

# Beer.create!(name: "Saison Dupont", style: "Blond Farmhouse Ale", description: "A light, effervescent ale with a thick, creamy head and slightly sweet, spicy flavor. Earthy with lots of yeast.", image_url: "https://beerconnoisseur.com/sites/default/files/styles/beer_page_245w/public/beer/saison-dupont-cork.jpg?itok=q3y3_z07")

# Beer.create!(name: "Wild Onion Pub Drago", style: "Russian Imperial Stout", description: "A deep, dark, classic stout. Big and boozy with moderate carbonation. Rich and full-bodied.", image_url: "https://onionbrewery.com/wp-content/uploads/2019/07/drago.png")

# Beer.create!(name: "Dogfish Head Noble Rot", style: "Beer-Wine Hybrid", description: "Made with grape must, this saison-like beer has a spicy white wine body and dry, tart finish. Excellent with food and even better if you can find the oak-aged version", image_url: "https://www.dogfish.com/files/media/styles/beer_style/public/beer/NobleRot.jpg?itok=VvWHHCha")

# Beer.create!(name: "Weihenstephaner Hefe Weissbier", style: "Classic Wheat beer", description: "From one of the oldest breweries in Germany, this fruity, light wheat beer is a classic and perfect with food.", image_url: "https://www.weihenstephaner.de/fileadmin/_processed_/f/0/csm_HWB_4b5ee6204e.png")

Pairing.create!(recipe_id: 1, beer_id: 4)
Pairing.create!(recipe_id: 2, beer_id: 3)
Pairing.create!(recipe_id: 3, beer_id: 5)
Pairing.create!(recipe_id: 4, beer_id: 1)
Pairing.create!(recipe_id: 5, beer_id: 2)